import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import BottomButton from "@/components/BottomButton";
import DaySelectorButton from "@/components/DaySelectorButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background-white`}
      >
        <Header />
        <div className="p-600 flex flex-col w-full ">
          <DaySelectorButton />
          {children}
        </div>
        <div>
          <BottomButton buttonTitle="확인" />
        </div>
      </body>
    </html>
  );
}
